name: Update build scripts

on:
  schedule:
    - cron: 0 */12 * * *
  workflow_dispatch:

jobs:
  update-build-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up PATH
        run: |
          echo "${ANDROID_HOME}/build-tools/30.0.1" >> $GITHUB_PATH
      - name: Set up JDK 16
        uses: actions/setup-java@v1
        with:
          java-version: 16
      - name: Update build script
        run: |
          java -jar simpleupdater.jar -Rnekit508/mindustry-mod-template
      - name: Commit changes
        run: |
          git config --global user.email "no-reply@github.com"
          git config --global user.name "GitHub Actions"
          git add --all
          git commit -m "[AUTO] Update build script"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push